Sprint3
ClevertecFrontendLab/AnastasiyaPoleshuk pull request #1
Opened 2023-02-15 09:30 UTC by AnastasiyaPoleshuk

2023-02-15 09:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676453580/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676453580/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676453580/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676453580/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676453580/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676453580/main-loading.png)

2023-02-15 09:46 UTC, SergeyGlazun requested changes

2023-02-15 09:46 UTC, SergeyGlazun commented on .editorconfig
> +root = true
![image](https://user-images.githubusercontent.com/70904466/218992102-ba9ea8e1-db3f-48ae-9272-781135b1590b.png)
при ошибки должно быть окно об уведомлении об ошибки и строки поиска вроде не должно быть на макете

2023-02-15 10:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676455272/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676455272/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676455272/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676455272/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676455272/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676455272/main-loading.png)

2023-02-15 10:02 UTC, AnastasiyaPoleshuk commented on .editorconfig
> +root = true
Локально окно уведомления появляется. Возможно скриншот делается раньше чем, оно успевает отобразится. Там анимация с задержкой в 0.5s

2023-02-15 10:08 UTC, SergeyGlazun requested changes

2023-02-15 10:08 UTC, SergeyGlazun commented on src/components/Card/Card.tsx
>  import { useContext } from 'react';
![image](https://user-images.githubusercontent.com/70904466/218997305-2747a6a1-3a70-440a-a2c4-c955aa375064.png)
при ошибки должно появиться уведомление как на макете

2023-02-15 10:08 UTC, SergeyGlazun commented on src/components/Card/Card.tsx
>  import { useDispatch, useSelector } from 'react-redux';
![image](https://user-images.githubusercontent.com/70904466/218997583-f215662a-1836-4332-b922-587d477b5ac1.png)
и тут уведомление должно быть свертись с макетом

2023-02-15 10:41 UTC, AnastasiyaPoleshuk commented on src/components/Card/Card.tsx
>  import { useDispatch, useSelector } from 'react-redux';
Локально окно уведомления появляется. Возможно скриншот делается раньше чем, оно успевает отобразится. Там анимация с задержкой в 0.5s

![image](https://user-images.githubusercontent.com/88983017/219005146-28198001-5062-48f4-b0a2-74080bbfaaf0.png)

2023-02-15 10:41 UTC, AnastasiyaPoleshuk commented on src/components/Card/Card.tsx
>  import { useContext } from 'react';
![image](https://user-images.githubusercontent.com/88983017/219004346-c90af6a0-ed63-4321-9c67-ef9aca08d448.png)

оно отображается позжею после загрузки т к при ошибке происходит переадресация на главную страницу

2023-02-16 09:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676538829/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676538829/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676538829/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676538829/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676538829/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676538829/main-loading.png)

2023-02-16 11:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676547490/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676547490/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676547490/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676547490/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676547490/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676547490/main-loading.png)

2023-02-16 11:46 UTC, SergeyGlazun requested changes

2023-02-16 11:46 UTC, SergeyGlazun commented on .eslintrc.js
> +    extends: [require.resolve('arui-presets-lint/eslint'), 'plugin:react/jsx-runtime'],
![image](https://user-images.githubusercontent.com/70904466/219356292-dabb9027-57bf-4423-95f2-528baec9b1fb.png)
ошибка пришла а загрузка продолжаеться

2023-02-16 11:46 UTC, SergeyGlazun commented on .eslintrc.js
> +    parserOptions: {
![image](https://user-images.githubusercontent.com/70904466/219356404-38aad433-5b37-4e03-9f8b-4eacf02e0a61.png)
тоже самое данные пришли а загрузка идет еще, проверти количество запросов сколько у вас

2023-02-16 11:46 UTC, SergeyGlazun commented on .eslintrc.js
> +    },
![image](https://user-images.githubusercontent.com/70904466/219356620-5bc4ca33-ef98-42ea-8a7c-6d0961fe7be2.png)

2023-02-16 16:07 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676563662/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676563662/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676563662/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676563662/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676563662/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676563662/main-loading.png)

2023-02-16 16:23 UTC, SergeyGlazun requested changes

2023-02-16 16:23 UTC, SergeyGlazun commented on src/components/ErrorModal/ErrorModal.scss
![image](https://user-images.githubusercontent.com/70904466/219426070-c4ae20a3-ec5d-419a-a566-8520d3f84aea.png)
тут должна быть навигация, посмотрите как на макете

2023-02-16 16:32 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676565167/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676565167/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676565167/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676565167/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676565167/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnastasiyaPoleshuk/1676565167/main-loading.png)

2023-02-16 16:36 UTC, SergeyGlazun approved these changes

2023-02-16 16:37 UTC, merged